// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate, db pull, etc.) needs a direct, non-pooled connection —
    // see .env for why this differs from the app's runtime DATABASE_URL.
    url: process.env["DIRECT_URL"],
  },
});
